doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/User/Entity/'
                prefix: 'App\User'
                alias: Customer
            Customer:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Customer/Entity/'
                prefix: 'App\Customer'
                alias: Customer
            Address:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Address/Entity/'
                prefix: 'App\Address'
                alias: Address
            Smartphone:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Smartphone/Entity/'
                prefix: 'App\Smartphone'
                alias: Smartphone
