version: '3'

services:

  db:
    container_name: mariadb
    build: ./mariadb
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USER}
    command:
        mysqld --sql-mode=""

  phpmyadmin:
      container_name: pma
      image: phpmyadmin/phpmyadmin
      environment:
          - UPLOAD_LIMIT=1024M
      depends_on:
          - db
      ports:
          - 8080:80

  php:
    container_name: php
    build:
      context: ./php
    environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
    ports:
      - '9000:9000'
    volumes:
      - ${APP_FOLDER}:/var/www
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ${APP_FOLDER}:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database